In [ ]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\Hamsa\AppData\Local\Programs\Python\Python313\Lib\site-packages (3.0.0)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\Hamsa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\Hamsa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\Hamsa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\Hamsa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
df = pd.read_csv("../data/aqi_data.csv")
df.head()

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Delhi,01-01-2015,153.3,241.7,182.9,33.0,81.3,38.5,1.87,64.5,83.6,18.93,20.81,8.32,204.5,Severe
1,Mumbai,01-01-2015,70.5,312.7,195.0,42.0,122.5,31.5,7.22,83.8,108.0,2.01,19.41,2.86,60.9,Satisfactory
2,Chennai,01-01-2015,174.1,275.4,56.2,68.8,230.9,28.5,8.56,60.8,43.9,19.07,10.19,9.63,486.5,Severe
3,Kolkata,01-01-2015,477.2,543.9,14.1,76.4,225.9,45.6,2.41,42.1,171.1,9.31,11.65,9.39,174.4,Very Poor
4,Bangalore,01-01-2015,171.6,117.7,123.3,12.4,61.9,49.7,1.26,79.7,164.3,6.04,12.74,9.59,489.7,Good

In [ ]:
pip install --upgrade pip

Requirement already satisfied: pip in C:\Users\Hamsa\AppData\Local\Programs\Python\Python313\Lib\site-packages (26.0.1)
Note: you may need to restart the kernel to use updated packages.

In [ ]:
import pandas as pd

df = pd.read_csv("../data/aqi_data.csv")
df.head()

,City,Datetime,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Delhi,01-01-2015,153.3,241.7,182.9,33.0,81.3,38.5,1.87,64.5,83.6,18.93,20.81,8.32,204.5,Severe
1,Mumbai,01-01-2015,70.5,312.7,195.0,42.0,122.5,31.5,7.22,83.8,108.0,2.01,19.41,2.86,60.9,Satisfactory
2,Chennai,01-01-2015,174.1,275.4,56.2,68.8,230.9,28.5,8.56,60.8,43.9,19.07,10.19,9.63,486.5,Severe
3,Kolkata,01-01-2015,477.2,543.9,14.1,76.4,225.9,45.6,2.41,42.1,171.1,9.31,11.65,9.39,174.4,Very Poor
4,Bangalore,01-01-2015,171.6,117.7,123.3,12.4,61.9,49.7,1.26,79.7,164.3,6.04,12.74,9.59,489.7,Good

In [ ]:
df.shape

(18265, 16)

In [ ]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 18265 entries, 0 to 18264
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        18265 non-null  str
 1   Datetime    18265 non-null  str
 2   PM2.5       18265 non-null  float64
 3   PM10        18265 non-null  float64
 4   NO          18265 non-null  float64
 5   NO2         18265 non-null  float64
 6   NOx         18265 non-null  float64
 7   NH3         18265 non-null  float64
 8   CO          18265 non-null  float64
 9   SO2         18265 non-null  float64
 10  O3          18265 non-null  float64
 11  Benzene     18265 non-null  float64
 12  Toluene     18265 non-null  float64
 13  Xylene      18265 non-null  float64
 14  AQI         18265 non-null  float64
 15  AQI_Bucket  18265 non-null  str
dtypes: float64(13), str(3)
memory usage: 2.2 MB

In [ ]:
df.isnull().sum()

City          0
Datetime      0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
CO            0
SO2           0
O3            0
Benzene       0
Toluene       0
Xylene        0
AQI           0
AQI_Bucket    0
dtype: int64

In [ ]:
df.dtypes

City              str
Datetime          str
PM2.5         float64
PM10          float64
NO            float64
NO2           float64
NOx           float64
NH3           float64
CO            float64
SO2           float64
O3            float64
Benzene       float64
Toluene       float64
Xylene        float64
AQI           float64
AQI_Bucket        str
dtype: object

In [ ]:
df['Datetime'] = pd.to_datetime(df['Datetime'], errors='coerce')

In [ ]:
df.dtypes

City                     str
Datetime      datetime64[us]
PM2.5                float64
PM10                 float64
NO                   float64
NO2                  float64
NOx                  float64
NH3                  float64
CO                   float64
SO2                  float64
O3                   float64
Benzene              float64
Toluene              float64
Xylene               float64
AQI                  float64
AQI_Bucket               str
dtype: object

In [ ]:
df = df.dropna(subset=['Datetime'])

In [ ]:
df['Year'] = df['Datetime'].dt.year
df['Month'] = df['Datetime'].dt.month
df['DayOfWeek'] = df['Datetime'].dt.dayofweek

In [ ]:
df[['Datetime', 'Year', 'Month', 'DayOfWeek']].head()

    Datetime  Year  Month  DayOfWeek
0 2015-01-01  2015      1          3
1 2015-01-01  2015      1          3
2 2015-01-01  2015      1          3
3 2015-01-01  2015      1          3
4 2015-01-01  2015      1          3

In [ ]:
!pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\Hamsa\AppData\Local\Programs\Python\Python313\Lib\site-packages (1.8.0)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Hamsa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (2.4.1)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\Hamsa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.17.0)
Requirement already satisfied: joblib>=1.3.0 in C:\Users\Hamsa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.2.0 in C:\Users\Hamsa\AppData\Local\Programs\Python\Python313\Lib\site-packages (from scikit-learn) (3.6.0)

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
df['City_encoded'] = le.fit_transform(df['City'])

In [ ]:
df[['City', 'City_encoded']].head()

        City  City_encoded
0      Delhi             2
1     Mumbai             4
2    Chennai             1
3    Kolkata             3
4  Bangalore             0

In [ ]:
# Drop columns we should not use for training
df = df.drop(columns=['City', 'AQI_Bucket', 'Datetime'])

df.head()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,Year,Month,DayOfWeek,City_encoded
0,153.3,241.7,182.9,33.0,81.3,38.5,1.87,64.5,83.6,18.93,20.81,8.32,204.5,2015,1,3,2
1,70.5,312.7,195.0,42.0,122.5,31.5,7.22,83.8,108.0,2.01,19.41,2.86,60.9,2015,1,3,4
2,174.1,275.4,56.2,68.8,230.9,28.5,8.56,60.8,43.9,19.07,10.19,9.63,486.5,2015,1,3,1
3,477.2,543.9,14.1,76.4,225.9,45.6,2.41,42.1,171.1,9.31,11.65,9.39,174.4,2015,1,3,3
4,171.6,117.7,123.3,12.4,61.9,49.7,1.26,79.7,164.3,6.04,12.74,9.59,489.7,2015,1,3,0

In [ ]:
df.columns

Index(['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3',
       'Benzene', 'Toluene', 'Xylene', 'AQI', 'Year', 'Month', 'DayOfWeek',
       'City_encoded'],
      dtype='str')

In [ ]:
X = df.drop(columns=['AQI'], errors='ignore')
y = df['AQI']

In [ ]:
print(X.shape)
print(y.shape)
X.head()

(7200, 16)
(7200,)

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,Year,Month,DayOfWeek,City_encoded
0,153.3,241.7,182.9,33.0,81.3,38.5,1.87,64.5,83.6,18.93,20.81,8.32,2015,1,3,2
1,70.5,312.7,195.0,42.0,122.5,31.5,7.22,83.8,108.0,2.01,19.41,2.86,2015,1,3,4
2,174.1,275.4,56.2,68.8,230.9,28.5,8.56,60.8,43.9,19.07,10.19,9.63,2015,1,3,1
3,477.2,543.9,14.1,76.4,225.9,45.6,2.41,42.1,171.1,9.31,11.65,9.39,2015,1,3,3
4,171.6,117.7,123.3,12.4,61.9,49.7,1.26,79.7,164.3,6.04,12.74,9.59,2015,1,3,0